services:
  temporal:
    image: temporalio/auto-setup:latest
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=rurkiJgD7cZ0Ceejgjeq5IV4ydeseZtb
      - POSTGRES_SEEDS=wvszpfhmo27saxn0bfbwokze
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=false
    networks:
      - coolify
      - default

  temporal-ui:
    image: temporalio/ui:latest
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=https://redes.radioinsular.es
    networks:
      - coolify
      - default

networks:
  coolify:
    external: true
  default:
    driver: bridge
